# Generated by Django 5.0 on 2023-12-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='keywords',
            field=models.TextField(default='Popular'),
        ),
    ]
